### PR TITLE
Switch PHP 8.3 to stable

### PR DESCRIPTION
**Pull request by johnbillion**

### CODE REVIEW

**Review by desrosj — APPROVED** [review]
Thanks for this! I went to make this change late last week, but docker-library/php had not yet been updated.

Any reason why we shouldn't also update `$latest` to be `8.3` at the same time?

I was hoping we could add the PECL extensions in there now as well. `imagick` and `memcached` have not yet been updated, and xDebug has `3.3.0alpha2` out which adds support for PHP 8.3. So just need to follow up a bit later for those.

**Comment by johnbillion** [comment]
I noticed memcached wasn't available and caused the container to fail to start when trying to run it with `LOCAL_PHP_MEMCACHED` in the core repo.

I didn't bump the latest as this was done separately for 8.2: #60

**Comment by desrosj** [comment]
I'm fine with separately. The main reason why that was separate was due to 8.0 and 8.1 never being set to `latest`. I wouldn't mind establishing the practice of bumping latest at the same time as GA for a new version, but it may best to evaluate any side effects each time.

**Review by jrfnl — APPROVED** [review]
> I went to make this change late last week, but docker-library/php had not yet been updated.

Dito ;-) Still have the Docker page open in a tab waiting for it to be available. Thanks @johnbillion for spotting it!

**Comment by jrfnl** [comment]
> I'm fine with separately. The main reason why that was separate was due to 8.0 and 8.1 never being set to `latest`. I wouldn't mind establishing the practice of bumping latest at the same time as GA for a new version, but it may best to evaluate any side effects each time.

I'd say: let's make it `latest` once the extensions are available.

Note: at this time, the WP Core `xdebug` test group is still not being run on PHP 8.3 due to there not being a stable version supporting 8.3 available. Along the same lines, I expect a number of `imagick` tests are currently being skipped.

**Review by szepeviktor — APPROVED** [review]

**Comment by jrfnl** [comment]
FYI: Xdebug 3.3.0 has been released: https://xdebug.org/announcements/2023-11-30

**Comment by jrfnl** [comment]
Just saw this - Imagick is not (yet) PHP 8.3 compatible: https://github.com/Imagick/imagick/pull/641

**Pull request merged**
