### PR TITLE
Add `rsync` dependency to php Dockerfile

### PR DESCRIPTION
**Pull request by getsource**
Adds `rsync` to all PHP Dockerfiles to allow core TravisCI to
successfuly submit results of tests to the distributed hosting tests.

See: /WordPress/wpdev-docker-images/issues/22

### CODE REVIEW

**Comment by pento** [comment]
You'll need to do it in a branch on this repo, rather than a fork, so that Travis secrets are decrypted properly. 🙂

**Comment by getsource** [comment]
Thank you! That's good to know.
I don't believe I have access to do that on this repo.

**Comment by pento** [comment]
My bad, I thought I'd added the committers team to this repo when I created it. Fixed!

**Comment by getsource** [comment]
No worries. Got it -- Thanks for your help!

Since the PR would come from the branch on this repo, going to close this one.

**Pull request closed without merging**
