### PR TITLE
Xdebug: update to version 3.2.1

### PR DESCRIPTION
**Pull request by jrfnl**
... which was released in March.

Refs:
* https://xdebug.org/announcements/2023-03-21
* https://xdebug.org/updates#x_3_2_1

---

Note: the build failure is unrelated to this PR and looks like it has been happening for a few weeks....

### CODE REVIEW

**Comment by jrfnl** [comment]
FYI: I have a PR to add PHP 8.3 to the images ready as well, but that one would conflict with this one, so is waiting for this PR to be merged.

**Comment by jrfnl** [comment]
Rebased without changes in hopes that the build will now pass (after PR #112).

**Review by desrosj — APPROVED** [review]

**Comment by desrosj** [comment]
Thanks @jrfnl!

**Comment by jrfnl** [comment]
@desrosj Eh.. does that mean this can be merged now ? (I don't usually merge my own PRs)

**Comment by desrosj** [comment]
That's right! I'll go ahead and merge it.

**Comment by jrfnl** [comment]
Thanks! Next PR upcoming.

**Pull request merged**
