### PR TITLE
Add PHP 8.2 containers

### PR DESCRIPTION
**Pull request by desrosj**
PHP 8.2 is only in the alpha phase, but the 8.2-rc container will continue to update as new pre-release versions are published.

Note: this does not include the Memcached, xDebug, or Imagick extensions. In my local testing, I found the container would not build correctly.

### CODE REVIEW

**Comment by jrfnl** [comment]
I'm not sure PHPUnit should be included yet as they have not officially declared PHP 8.2 compatibility yet, let alone which versions will be supported.

**Comment by desrosj** [comment]
@jrfnl I'm fine either way! My thinking for including them was that PHPUnit does test against PHP 8.2 in their CI even though support is not declared.

**Comment by jrfnl** [comment]
P.S.: I'm not the right person to review as I don't use Docker myself.

**Comment by desrosj** [comment]
I've tested all of the generated containers, and everything seems right to me.

The test suite does run using both PHPUnit 8.x and 9.x (of course with errors and failures). Even though it hasn't officially been declared which versions will support PHP 8.2, I think it's reasonable to make both versions available since PHPUnit itself is currently testing against 8.2.

**Comment by jrfnl** [comment]
For anyone interested, here is the meta ticket about making WordPress compatible with PHP 8.2: https://core.trac.wordpress.org/ticket/56009

**Comment by jrfnl** [comment]
FYI: Xdebug 3.2.0 will be compatible with PHP 8.2 and alpha builds are available for testing at the moment: https://xdebug.org/download/historical

Also see:
* https://xdebug.org/announcements/2022-07-20
* https://xdebug.org/announcements/2022-07-25

**Pull request merged**
